@startuml system_context
!include <C4/C4_Container>

Person(User, "User", "Application user")
System_Boundary(SysBound, "Newspaper scraper System") {
  System(WebApp, "Newspaper scraper System", "Allows users to search topics, gathers information from different newspapers about them, and provides visualization and comparison features for its contents")

}
System(NewsWebApp1, "Newspaper Web Application 1", "A newspapper web application")
System(NewsWebApp2, "Newspaper Web Application N", "A newspapper web application")

Rel(User, WebApp, "uses")
Rel(WebApp, NewsWebApp1, "Gathers contents")
Rel(WebApp, NewsWebApp2, "Gathers contents")

@enduml

